pipelines:
  - name: basic_sleep
    steps:
      - name: basic_sleep
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - sleep 2m
