
pipelines:
  - name: basic_parallel
    steps:
      - name: start
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
      - name: p1
        type: Bash
        configuration:
          nodePool: u16-on-demand
          runtime:
            type: host
          inputSteps:
            - name: start
        execution:
          onExecute:
            - printenv
      - name: p2
        type: Bash
        configuration:
          nodePool: u16-on-demand
          runtime:
            type: host
          inputSteps:
            - name: start
        execution:
          onExecute:
            - printenv
      - name: p3
        type: Bash
        configuration:
          nodePool: c7-on-demand
          runtime:
            type: host
          inputSteps:
            - name: start
        execution:
          onExecute:
            - printenv
      - name: p4
        type: Bash
        configuration:
          nodePool: c7-on-demand
          runtime:
            type: host
          inputSteps:
            - name: start
        execution:
          onExecute:
            - printenv
      - name: end
        type: Bash
        configuration:
          inputSteps:
            - name: p1
            - name: p2
            - name: p3
            - name: p4
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
