resources:
  - name: git1
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: bharath_github
      branches:
        include: master
  - name: git2
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: bharath_github
      branches:
        include: master
      files:
        include: \btestdir\/file1\b
  - name: git3
    type: GitRepo
    configuration:
      path: ~bharathu/poc
      gitProvider: bharath_bbs
      branches:
        include: master
  - name: git4
    type: GitRepo
    configuration:
      path: bharath92/multibranch-pipelines
      gitProvider: bharath_github
      branches:
        include: \b.+\b
  - name: git5
    type: GitRepo
    configuration:
      path: bharath92/pipelines
      gitProvider: bharath_github
      branches:
        include: basic2
  - name: git6
    type: GitRepo
    configuration:
      path: bharath92/pipelines
      gitProvider: bharath_github
      branches:
        include: master
      buildOn:
        commit: false
        pullRequestCreate: true
     
pipelines:
  - name: check1
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: git1
        execution:
          onExecute:
            - add_pipeline_variables "step=$step_id"
  - name: check2
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: git2
        execution:
          onExecute:
            - echo hi
  - name: check3
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: git3
        execution:
          onExecute:
            - echo hi
  - name: check4
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: git4
        execution:
          onExecute:
            - echo hi
  - name: check5
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: git6
        execution:
          onExecute:
            - echo $res_git6_shaData
            - echo $res_git6_gitRepoFullName
            - export is_fork=true
            - |
              if $res_git6_isPullRequest; then
                head=$(echo "$res_git6_shaData" | jq -r .pullRequestRepoFullName)
                base="$res_git6_gitRepoFullName"
                if [ "$head" == "$base" ]; then
                  is_fork=false
                fi
              fi
            - echo $is_fork
            - isPrivateRepository=$(find_resource_variable "$resourceName" isPrivateRepository)
            - pullRequestSourceUrl=$(find_resource_variable "$resourceName" pullRequestSourceUrl)
            - |
              if isPrivateRepository; then
                cloneUrl=$(find_resource_variable "$resourceName" gitRepoRepositorySshUrl)
              else
                cloneUrl=$(find_resource_variable "$resourceName" gitRepoRepositoryHttpsUrl)
              fi
            - |
              if [ "$cloneUrl" != "$pullRequestSourceUrl" ]; then
                export isFork=true;
              else
                export isFork=false;
              fi
            -  echo $isFork
                      
