pipelines:
  - name: matrix
    steps:
      - name: matrix
        type: Matrix
        stepletMultipliers:
          environmentVariables:
            - foo: 2
            - foo: 4
        configuration:
#           multiNode: true
          runtime:
            type: host
        execution:
          onExecute:
            - echo $foo
            - for (( k = 0; k < 20; ++k )); do   sleep $(( foo*k )); done
