start: &start
  - echo start
  - echo 11
  - echo 2aa

resources:
  - name: basicgit
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master
  - name: basicgit2
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master
      cloneProtocol: https
pipelines:
#   - name: testaaaa
#     steps:
#       - name: testaaaa
#         type: Bash
#         execution:
#           onExecute:
#             - echo $UID
  - name: basic_git
    steps:
      - name: basic_git
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-u18node
                tag: "16"
                autoPull: true
          inputResources:
            - name: basicgit
        execution:
          onStart: *start
          onExecute:
            - echo $UID
      - name: basic_git_2
        type: Bash
        configuration:
          inputSteps:
            - name: basic_git
        execution:
          onStart:
            - git --version
            - git clone --progress --verbose https://github.com/Bharath92/pipelines.git
      - name: basic_git_3
        type: Bash
        configuration:
          inputSteps:
            - name: basic_git
          inputResources:
            - name: basicgit2
        execution:
          onStart:
            - git --version
