pipelines:
  - name: basic1
    steps:
      - name: basic
        type: Matrix
        stepletMultipliers:
          environmentVariables:
            foo: bar
            boo: foo
        configuration:
          multiNode: true
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - echo lol
            - add_pipeline_variables foo=bar
            - echo loool
