pipelines:
  - name: basic1
    steps:
      - name: basic
        type: Matrix
        configuration:
          stepletMultipliers:
            environmentVariables:
              foo: bar
              boo: foo
          multiNode: true
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - echo lol
            - add_pipeline_variables foo=bar
            - echo loool
