resources:
  - name: git
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master 
  - name: cron
    type: CronTrigger
    configuration:
      interval: '*/2 * * *'

pipelines:
  - name: basic1
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
#           inputResources:
#             - name: cron
        execution:
          onExecute:
            - printenv
            - echo lol
            - add_pipeline_variables foo=bar
            - echo loool
      - name: second
        type: DockerBuild
        configuration:
          runtime:
            type: host
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: foo
          dockerImageTag: foo
          inputResources:
            - name: git
          inputSteps:
            - name: basic
#       - name: third
#         type: Bash
#         configuration:
#           #inputResources:
#           #  - name: git
#           inputSteps:
#             - name: basic
#             - name: second
#           environmentVariables:
#             foo: bar
#           runtime:
#             type: host
#         execution:
#           onExecute:
#             - echo $foo
          
