
pipelines:
  - name: basic_again
    steps:
      - name: test
        type: Bash
        configuration:
          nodePool: u16-on-demand
          runtime:
            type: host
        execution:
          onExecute:
            - printenv

