pipelines:
  - name: simple
    steps:
      - name: simple
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
