resources:
  - name: repro
    type: GitRepo
    configuration:
      path: bharath92/pipelines
      gitProvider: bharath_github
      branches:
        include: master

pipelines:
  - name: repro
    steps:
      - name: basic
        type: Bash
        configuration:
          inputResources:
            - name: repro
          runtime:
            type: host
        execution:
          onExecute:
            - echo hiii
