resources:
  - name: git
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master 

pipelines:
  - name: basic
    steps:
      - name: step1
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - sleep 2m
      - name: step2
        type: Bash
        configuration:
          runtime:
            type: host
          inputSteps:
            - name: step1
          inputResources:
            - name: git
        execution:
          onExecute:
            - sleep 2m
      - name: step3
        type: Bash
        configuration:
          runtime:
            type: host
          inputSteps:
            - name: step2
          inputResources:
            - name: git
        execution:
          onExecute:
            - sleep 2m
