resources:
  - name: cron
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'
  - name: basicgit2
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master
   - name: basicgit3
    type: GitRepo
    configuration:
      path: bharath92/pipelines
      gitProvider: github
      branches:
        include: master
pipelines:
  - name: basic_git2
    steps:
      - name: basic_git2
        type: Bash
        configuration:
          outputResources:
            - name: cron
          inputResources:
            - name: basicgit2
          runtime:
            type: host
        execution:
          onExecute:
            - echo hi
            - write_output cron foo=$run_number
