pipelines:
  - name: test
    steps:
      - name: test
        type: PowerShell
        configuration:
          runtime:
            type: host
          nodePool: win_2019
          integrations:
            - name: s_artifactory
            - name: bgithub
        execution:
          onExecute:
            - cleanup_jfrog_cli --server-name s_artifactory
