pipelines:
  - name: basic_again
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: drydock/pipelines-u16node
                tag: master
                sourceRepository: bharathdockervirtual
                registry: localart
        execution:
          onExecute:
            - echo 'Hello World!!!'
          
