resources:
  - name: buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: lol2
      buildNumber: 1
pipelines:
  - name: basic
    steps:
      - name: basic1
        type: Bash
        configuration:
          inputResources:
            - name: buildInfo
        execution:
          onExecute:
            - printenv
      - name: basic2
        type: Bash
        configuration:
          inputSteps:
            - name: basic1
        execution:
          onExecute:
            - printenv

