pipelines:
  - name: c7_test
    steps:
      - name: step1
        type: Bash
        configuration:
          affinityGroup: foo
          nodePool: test_c7
          runtime:
            type: host
        execution:
          onExecute:
            - echo hii
            - sudo echo lol
      - name: step2
        type: Bash
        configuration:
          affinityGroup: foo
          inputSteps:
            - name: step1
          nodePool: test_c7
          runtime:
            type: host
        execution:
          onExecute:
            - echo hii
            - sudo echo lol
      - name: step3
        type: Bash
        configuration:
          inputSteps:
            - name: step2
          nodePool: test_c7
          runtime:
            type: host
        execution:
          onExecute:
            - echo hii
            - sudo echo lol
  - name: u16_test
    steps:
      - name: step1
        type: Bash
        configuration:
          affinityGroup: foo
          nodePool: test_u16
          runtime:
            type: host
        execution:
          onExecute:
            - echo hii
            - sudo echo lol
      - name: step2
        type: Bash
        configuration:
          affinityGroup: foo
          inputSteps:
            - name: step1
          nodePool: test_u16
          runtime:
            type: host
        execution:
          onExecute:
            - echo hii
            - sudo echo lol
      - name: step3
        type: Bash
        configuration:
          inputSteps:
            - name: step2
          nodePool: test_u16
          runtime:
            type: host
        execution:
          onExecute:
            - echo hii
            - sudo echo lol
  - name: u18_test
    steps:
      - name: step1
        type: Bash
        configuration:
          affinityGroup: foo
          nodePool: test_u18
          runtime:
            type: host
        execution:
          onExecute:
            - echo hii
            - sudo echo lol
      - name: step2
        type: Bash
        configuration:
          affinityGroup: foo
          inputSteps:
            - name: step1
          nodePool: test_u18
          runtime:
            type: host
        execution:
          onExecute:
            - echo hii
            - sudo echo lol
      - name: step3
        type: Bash
        configuration:
          inputSteps:
            - name: step2
          nodePool: test_u18
          runtime:
            type: host
        execution:
          onExecute:
            - echo hii
            - sudo echo lol
