resources:
  - name: git1
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: bharath_github
      branches:
        include: master
  - name: git2
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: bharath_github
      branches:
        include: master
      files:
        include: \btestdir\/file1\b
pipelines:
  - name: check1
    steps:
      - name: basic
        type: Bash
        configuration:
          inputResources:
            - name: git1
        execution:
          onExecute:
            - echo hi
  - name: check2
    steps:
      - name: basic
        type: Bash
        configuration:
          inputResources:
            - name: git2
        execution:
          onExecute:
            - echo hi
