pipelines:
  - name: basic
    steps:
      - name: basic
        type: Bash
        configuration:
          environmentVariables:
            foo: bar
          runtime:
            type: host
        execution:
          onExecute:
            - echo $foo
      - name: second
        type: Bash
        configuration:
          inputSteps:
            - name: basic
          environmentVariables:
            foo: bar
          runtime:
            type: host
        execution:
          onExecute:
            - echo $foo
          
