 resources:
   - name: git_repro
     type: GitRepo
     configuration:
       path: bharath92/pipelines
       gitProvider: bharath_github
       branches:
         include: repro

pipelines:
  - name: repro
    steps:
      - name: basic
        type: Bash
        configuration:
          inputResources:
            - name: git
          runtime:
            type: host
        execution:
          onExecute:
            - echo hi
          
