resources:
  - name: github_1
    type: GitRepo
    configuration:
      path: bharath92/gitIssues
      gitProvider: bharath_github
      buildOn:  # optional
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: true
  - name: bitbucket_1
    type: GitRepo
    configuration:
      path: bharath92/sample-runsh
      gitProvider: bitbucket
      buildOn:  # optional
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: true
  - name: gitlab_1
    type: GitRepo
    configuration:
      path: Bharath92/samplePyt
      gitProvider: gitlab
      buildOn:  # optional
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: true
  - name: my_aql
    type: Aql
    configuration:
      sourceArtifactory: art
      query: "lol"
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildNumber: 1
      buildName: lol
  - name: fileIntegrationResource
    type: FileSpec
    configuration:      
      sourceArtifactory: art
  - name: imageName
    type: Image
    configuration:
       registry: art
       sourceRepository: lol
       imageName: imageRepo/imageName
       imageTag: lol 
       autoPull: true
  - name: webhookIntegrationResource
    type: Webhook
    configuration:
      webhookName: web
      payload: "lol"
  - name: vmIntegrationResource
    type: VmCluster
    configuration:
      sshKey: ssh
      targets:
        - 1.2.3.4

  - name: my_releaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: <string>
      version: <string
  - name: my_distributionRule
    type: DistributionRule
    configuration:
      sourceDistribution: dist      
      serviceName: "fasd"
      siteName: asfd
      cityName: afsd
      countryCodes:
        - afsd
  - name: kubeClusterIntegrationResource
    type: KubeCluster
    configuration:
      kubernetesConfig: kube







pipelines:
  - name: basic3
    steps:
      - name: test
        type: Bash
        configuration:
          inputResources:
            - name: github_1
            - name: bitbucket_1
            - name: gitlab_1
        execution:
          onExecute:
            - printenv

