pipelines:
  - name: my_pipeline
    configuration:
      environmentVariables:
        readOnly:
          env1: value1
          env2:
            default: value1
            description: env2 description
            values:
              - value1
              - value2
              - value3
    steps:
      - name: my_step
        type: Bash
        execution:
          onExecute:
            - printenv
        configuration:
          environmentVariables:
            step_env1:
              default: value1
              description: step env1 description
              values:
                - value1
                - value2
                - value3
              allowCustom: true
            step_env2: value2
      - name: my_second_step
        type: Bash
        execution:
          onExecute:
            - printenv
        configuration:
          inputSteps:
            - name: my_step
          environmentVariables:
            step_env2: value2
      - name: my_third_step
        type: Bash
        execution:
          onExecute:
            - printenv
        configuration:
          inputSteps:
            - name: my_second_step
          environmentVariables:
            step_env2: value2
