pipelines:
  - name: basic_fast_fail
    steps:
      - name: matrix_fast_fail
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          fastFail: true
          environmentVariables:
            - delay: 1
              fail: 'true'
            - delay: 10
              fail: 'true'
            - delay: 15
              fail: 'false'
            - delay: 20
              fail: 'false' 
        execution:
          onStart:
            - sleep "$delay"
          onExecute:
            - echo "I am on matrix step"
            - |
              [ $fail == 'false' ] 
            - ls -l .


