resources:
  - name: cron
    type: CronTrigger
    configuration:
      interval: '*/2 * * *'
pipelines:
  - name: version_test
    steps:
      - name: version_test_1
        type: Bash
        configuration:
          outputResources:
            - name: cron
          runtime:
            type: host
        execution:
          onExecute:
            - write_output cron "foo=$run_number"
      - name: version_test_2
        type: Bash
        configuration:
          inputResources:
            - name: cron
          runtime:
            type: host
        execution:
          onExecute:
            - echo hi
