resources:
  - name: branchInclExcl
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master
        exclude: foo
      pullRequestSourceBranches:
        include: abc
        exclude: def
      pullRequestTargetBranches:
        include: qwerty
        exclude: poiuy
      buildOn:
        commit: true
        pullRequestCreate: true
        pullRequestClose: true
pipelines:
  - name: basic
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: branchInclExcl
        execution:
          onExecute:
            - echo foo
