pipelines:
  - name: basic
    steps:
      - name: basic
        type: Bash
        configuration:
          environmentVariables:
            foo: bar
#           runtime:
#             type: host
#             image:
#               auto:
#                 language: javad
#                 versions:
#                   - master
        execution:
          onExecute:
            - echo 1
          
