resources:
  - name: reportsFS_x8664_C7
    type: FileSpec
    configuration:
      sourceArtifactory: entArt
      pattern: "pipelines-artifacts/reports/reports-x86_64-CentOS_7-*.tar.gz"
      recursive: false
pipelines:
  - name: basic_c7
    steps:
      - name: basic
        type: Bash
        configuration:
          inputResources:
            - name: reportsFS_x8664_C7
          runtime:
            type: image
            image:
              custom:
                name: pipelines-docker.jfrog.io/jfrog/pipelines-c7
                tag: base
        execution:
          onExecute:
            - echo 1
          
