resources:
  - name: basicgit
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master
pipelines:
  - name: basic_git
    steps:
      - name: basic_git
        type: Bash
        configuration:
          runtime:
            type: image
#           inputResources:
#             - name: basicgit
        execution:
          onExecute:
            - echo hiii
            - ls -al $run_dir
            - touch /tmp/foo
            - touch $run_dir/foo
            - curl http://10.70.30.120:8082/pipelines/api/v1
            - printenv
            - mkdir -p test && mount /dev/sdb test
