resources:
  - name: extgit
    type: GitRepo
    configuration:
      path: bharath92/sample-runsh
      gitProvider: github
      branches:
        include: master
pipelines:
  - name: exttest
    steps:
      - name: ext1
        type: shippable/DockerBuild
        configuration:
          foo: aaaa
          inputResources:
            - name: extgit
      - name: ext2
        type: drydock/DockerPush
        configuration:
          foo: bharathdocker
          inputResources:
            - name: extgit
