pipelines:
  - name: basic
    steps:
      - name: basic1
        type: Bash
        execution:
          onExecute:
            - printenv
      - name: basic2
        type: Bash
        configuration:
          inputSteps:
            - name: basic1
        execution:
          onExecute:
            - printenv

