pipelines:
  - name: bigfiles
    steps:
      - name: trigger
        type: Bash
        configuration:
          nodePool: u16
          inputSteps:
            - name: trigger
        execution:
          onExecute:
             - wget https://norvig.com/big.txt --no-check-certificate
             - cat big.txt
      - name: parallel1
        type: Bash
        configuration:
          nodePool: u16dynamic
          inputSteps:
            - name: trigger
        execution:
          onExecute:
            - wget https://norvig.com/big.txt --no-check-certificate
            - cat big.txt
      - name: parallel2
        type: Bash
        configuration:
          nodePool: u16dynamic
          inputSteps:
            - name: trigger
        execution:
          onExecute:
             - wget https://norvig.com/big.txt --no-check-certificate
             - cat big.txt
      - name: parallel3
        type: Bash
        configuration:
          nodePool: u16dynamic
          inputSteps:
            - name: trigger
        execution:
          onExecute:
            - wget https://norvig.com/big.txt --no-check-certificate
            - cat big.txt
      - name: parallel4
        type: Bash
        configuration:
          nodePool: u18dynamic
          inputSteps:
            - name: trigger
        execution:
          onExecute:
             - wget https://norvig.com/big.txt --no-check-certificate
             - cat big.txt
      - name: parallel5
        type: Bash
        configuration:
          nodePool: u18dynamic
          inputSteps:
            - name: trigger
        execution:
          onExecute:
            - wget https://norvig.com/big.txt --no-check-certificate
            - cat big.txt
      - name: parallel6
        type: Bash
        configuration:
          nodePool: u18dynamic
          inputSteps:
            - name: trigger
        execution:
          onExecute:
             - wget https://norvig.com/big.txt --no-check-certificate
             - cat big.txt
      - name: parallel7
        type: Bash
        configuration:
          nodePool: c7dynamic
          inputSteps:
            - name: trigger
        execution:
          onExecute:
            - wget https://norvig.com/big.txt --no-check-certificate
            - cat big.txt
      - name: parallel8
        type: Bash
        configuration:
          nodePool: c7dynamic
          inputSteps:
            - name: trigger
        execution:
          onExecute:
            - wget https://norvig.com/big.txt --no-check-certificate
            - cat big.txt
      - name: parallel9
        type: Bash
        configuration:
          nodePool: c7dynamic
          inputSteps:
            - name: trigger
        execution:
          onExecute:
             - wget https://norvig.com/big.txt --no-check-certificate
             - cat big.txt
      - name: parallel10
        type: Bash
        configuration:
          nodePool: win_2019
          inputSteps:
            - name: trigger
        execution:
          onExecute:
            - wget https://norvig.com/big.txt --no-check-certificate
            - type big.txt
      - name: parallel11
        type: Bash
        configuration:
          nodePool: win_2019
          inputSteps:
            - name: trigger
        execution:
          onExecute:
             - wget https://norvig.com/big.txt --no-check-certificate
             - type big.txt
       - name: parallel12
         type: Bash
         configuration:
           nodePool: rhel7
           inputSteps:
             - name: trigger
         execution:
           onExecute:
             - wget https://norvig.com/big.txt --no-check-certificate
             - cat big.txt
