pipelines:
  - name: basic_podman
    steps:
      - name: basic_podman
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: localhost/podmaninsideimage
                tag: 0.0.1
                autoPull: false
        execution:
          onExecute:
            - docker info
            - docker run alpine ls
