pipelines:
  - name: matrix
    steps:
      - name: matrix
        type: Matrix
        stepletMultipliers:
          environmentVariables:
            - foo: 2
              bar: echo
            - foo: 1
              bar: abc
        configuration:
#           multiNode: true
          runtime:
            type: host
        execution:
          onExecute:
            - echo $foo
            - for (( k = 0; k < 5; ++k )); do   sleep $(( foo*k )); done
            - $bar
