
pipelines:
  - name: basic
    steps:
      - name: host
        type: Bash
        configuration:      
          runtime:
            type: host
        execution:
          onExecute:
            - gcloud --version
            - jfrog --version
            - aws --version
            - git --version
            - helm --version
