resources:
  - name: basicgit
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master
pipelines:
  - name: basic_git
    steps:
      - name: basic_git
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: basicgit
        execution:
          onExecute:
            - echo hiii
            - docker run --init --privileged -v /usr/local/bin/docker:/usr/bin/docker alpine ls
            - docker run --init --privileged -v --memory 16526684160 /run/user/1000/docker.sock:/var/run/docker.sock alpine ls
            - docker run --init --privileged -v /var/opt/jfrog/pipelines/data/basic_git/workspace:/var/opt/jfrog/pipelines/data/basic_git/workspace alpine ls
            - printenv
            - mkdir -p test && mount /dev/sdb test
