pipelines:
  - name: multibranch
    steps:
      - name: multibranch
        type: Bash
        configuration:
          runtime:      
            type: host
        execution:
          onExecute:
            - echo hi
