resources:
  - name: dockergit
    type: GitRepo
    configuration:
      path: bharath92/sample-runsh
      gitProvider: github
      branches:
        include: master
pipelines:
  - name: podman_docker
    steps:
      - name: podman_docker_build
        type: DockerBuild
        configuration:
          affinityGroup: podman
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 9f89d5e3528a.ngrok.io/bharathdocker/test
          dockerImageTag: ${run_number}
          integrations:
            - name: localart
          inputResources:
            - name: dockergit
          runtime:
            type: host
#             type: image
#             image:
#               custom:
#                 name: localhost/podmaninsideimage
#                 tag: 0.0.2
#                 autoPull: false
      - name: podman_docker_push
        type: DockerPush
        configuration:
          runtime:      
            type: host
          affinityGroup: podman
          targetRepository: bharathdocker
          integrations:
            - name: localart
          inputSteps:
            - name: podman_docker_build
        execution:
          onStart:
            - ln -s $(which podman) /usr/local/bin/docker
