pipelines:
  - name: sample
    steps:
      - name: sample
        type: sample
        configuration:
          foo: "yeah!!!"
      - name: bash
        type: Bash
        configuration:
          inputSteps:
            - name: sample
        execution:
          onExecute:
            - echo hi
      - name: secondSample
        type: sample
        configuration:
          foo: "yeah!!!"
        execution:
          onSuccess:
            - echo success

