pipelines:
  - name: managed
    steps:
      - name: u18
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - docker images
      - name: c07
        type: Bash
        configuration:
          nodePool: c07
        execution:
          onExecute:
            - docker images
      - name: u16
        type: Bash
        configuration:
          nodePool: u16
        execution:
          onExecute:
            - docker images
  - name: published
    steps:
      - name: u18cust
        type: Bash
        configuration:
          nodePool: u18cust
          runtime:
            type: host
        execution:
          onExecute:
            - docker images
