resources:
  - name: basicgit
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master
pipelines:
  - name: basic_git
    steps:
      - name: basic_git
        type: Bash
        configuration:
          inputResources:
            - name: basicgit
          runtime:
            type: host
        execution:
          onExecute:
            - echo hii
            - printenv
