resources:
  - name: testRes
    type: sampleResource
    syntaxVersion: 0.0.1
    configuration:
      resourceFoo: 1

pipelines:
  - name: sample
    steps:
      - name: testStep
        type: sampleStep
        syntaxVersion: 0.0.1
        configuration:
          foo: "yeah!!!"
          inputResources:
            - name: testRes
    
