pipelines:
  - name: basic_podman
    steps:
      - name: basic_podman
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: localhost/podmaninsideimage
                tag: 0.0.2
                autoPull: false
        execution:
          onExecute:
            - whoami
            - alias
            - docker info
            - docker run alpine ls
            - docker ps -a
            - docker rm -fv $(docker ps -aq)
            - docker ps -a
