resources:
#   - name: cron
#     type: CronTrigger
#     configuration:
#       interval: "*/2 * * * *"

pipelines:
  - name: basic_again
    steps:
      - name: test
        type: Bash
        configuration:
          #timeoutSeconds: 120
#           inputResources:
#             - name: cron
          nodePool: u16
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - sleep 5m

