resources:
  - name: cron
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'
  - name: basicgit2
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master
pipelines:
  - name: basic_git2
    steps:
      - name: basic_git2
        type: Bash
        configuration:
          outputResources:
            - name: cron
          inputResources:
            - name: basicgit2
          runtime:
            type: host
        execution:
          onExecute:
            - echo hi
            - write_output cron foo=$run_number
            - export x=$(find_resource_variable "cron" resourcePath)
            - echo "$x/cron.env"
            - cat $x/cron.env
            - sleep 10
            - sleep 10
            - sleep 10
