# resources:
#   - name: git
#     type: GitRepo
#     configuration:
#       path: bharath92/sample-runSh
#       gitProvider: github
#       branches:
#         include: master 
#   - name: cron
#     type: CronTrigger
#     configuration:
#       interval: '*/2 * * *'

pipelines:
  - name: basic1
    steps:
      - name: preprebasic
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - echo hi
            - echo $run_id > foo
            - add_pipeline_files foo foo
            - add_run_files foo foo
            - add_pipeline_variables test=$run_id
            - add_run_variables test=$run_id
      - name: prebasic
        type: Bash
        configuration:
          inputSteps:
            - name: preprebasic
          runtime:
            type: host
        execution:
          onExecute:
            - echo hi
      - name: prebasic2
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - echo hi
      - name: prebasic3
        type: shippable/sampleStep
        syntaxVersion: 1.1.1
        configuration:
          foo: foo
          runtime:
            type: host
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - echo hi
      - name: basicparallel
        type: Bash
        configuration:
          inputSteps:
            - name: basic
          affinityGroup: foo
          runtime:
            type: host
        execution:
          onExecute:
            - sleep 1m
      - name: basic2
        type: Bash
        configuration:
#           inputResources:
#             - name: git
          inputSteps:
            - name: basic
            - name: prebasic
            - name: prebasic2
            - name: prebasic3
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - echo hi
      - name: basic3
        type: Bash
        configuration:
          affinityGroup: foo
#           outputResources:
#             - name: cron
          inputSteps:
            - name: basic2
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
#             - write_output cron "foo=$run_number"
            - echo hi
      - name: basic4
        type: Bash
        configuration:
          affinityGroup: foo
          inputSteps:
            - name: basic3
            - name: basic2
            - name: basicparallel
            - name: leafbasic
            - name: anotherleaf
            - name: nonleafextension
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
      - name: leafbasic
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
#       - name: anotherleaf
#         type: shippable/sampleStep
#         syntaxVersion: 1.1.1
#         configuration:
#           foo: foo
#           runtime:
#             type: host
#       - name: nonleafextension
#         type: shippable/sampleStep
#         syntaxVersion: 1.1.2
#         configuration:
#           affinityGroup: foo
#           inputSteps:
#             - name: basic3
#           foo: foo
#           runtime:
#             type: host
#       - name: basic5
#         type: Bash
#         configuration:
#           nodePool: k8_node_pool
#           inputSteps:
#             - name: basic4
# #           runtime:
# #             type: host
#         execution:
#           onExecute:
#             - printenv
#             - curl -vvv http://localhost:2375/_ping
#             - sleep 1m
