resources:
  - name: go_gitRepo
    type: GitRepo
    configuration:
      path: bharath92/swampup-go-service
      gitProvider: bharath_github
  - name: svc_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: bharath_art
      buildName: svc_build
      buildNumber: 1

  - name: svc_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: bharath_art
      buildName: svc_build
      buildNumber: 1


pipelines:
  - name: demo_service
    steps:
      - name: bld_svc
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 34.66.107.45:8081/docker-local-test/gomicrosvc
          dockerImageTag: $run_number
          inputResources:
            - name: go_gitRepo
          integrations:
            - name: bharath_art

      - name: push_svc
        type: DockerPush
        configuration:
          targetRepository: docker-local-test
          integrations:
            - name: bharath_art
          inputSteps:
            - name: bld_svc

      - name: publish_svc_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: push_svc
          outputResources:
            - name: svc_build_info

      - name: promote_svc_build
        type: PromoteBuild
        configuration:
          targetRepository: promote-test
          inputSteps:
            - name: publish_svc_build
          integrations:
            - name: bharath_art
          inputResources:
            - name: svc_build_info
          outputResources:
            - name: svc_promoted_build_info

  - name: test_pipeline1
    steps:
      - name: step1
        type: Bash
        configuration:
          affinityGroup: same
          inputResources:
            - name: go_gitRepo
        execution:
          onExecute:
            - echo hi
            - sleep 1m
            - echo bi
        
      - name: step2
        type: Bash
        configuration:
          runtime:
            type: host
          affinityGroup: same
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo hi
            - sleep 1m

  - name: c7_demo_service
    steps:
      - name: c7_bld_svc
        type: DockerBuild
        configuration:
          nodePool: c07
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 34.66.107.45:8081/docker-local-test/gomicrosvc
          dockerImageTag: $run_number
          inputResources:
            - name: go_gitRepo
          integrations:
            - name: bharath_art

      - name: c7_push_svc
        type: DockerPush
        configuration:
          nodePool: c07
          targetRepository: docker-local-test
          integrations:
            - name: bharath_art
          inputSteps:
            - name: c7_bld_svc

      - name: c7_publish_svc_build
        type: PublishBuildInfo
        configuration:
          nodePool: c07
          inputSteps:
            - name: c7_push_svc
          outputResources:
            - name: svc_build_info

      - name: c7_promote_svc_build
        type: PromoteBuild
        configuration:
          nodePool: c07
          targetRepository: promote-test
          inputSteps:
            - name: c7_publish_svc_build
          integrations:
            - name: bharath_art
          inputResources:
            - name: svc_build_info
          outputResources:
            - name: svc_promoted_build_info

  - name: c7_test_pipeline1
    steps:
      - name: c7_step1
        type: Bash
        configuration:
          nodePool: c07
          affinityGroup: same
          inputResources:
            - name: go_gitRepo
        execution:
          onExecute:
            - echo hi
            - sleep 1m
            - echo bi
        
      - name: c7_step2
        type: Bash
        configuration:
          nodePool: c07
          runtime:
            type: host
          affinityGroup: same
          inputSteps:
            - name: c7_step1
        execution:
          onExecute:
            - echo hi
            - sleep 1m
            
