pipelines:
  - name: basic_cron
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - add_pipeline_variables run=$run_number
