resources:
  - name: basicgit
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master
pipelines:
  - name: basic_git
    steps:
      - name: basic_git
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: bharath92/pipelines
                tag: min
                options: -u nobody|65534
#           inputResources:
#             - name: basicgit
        execution:
          onExecute:
            - ls -la /var/opt/jfrog/pipelines
            - touch  /var/opt/jfrog/pipelines/boo
            - echo hiii
            - ls -al $run_dir
            - ls -al $pipeline_workspace_dir
            - lsblk
#             - chown -R 1000:1000 $pipeline_workspace_dir/
#             - chmod -R 0777 $run_dir
            - touch /tmp/foo
            - touch $run_dir/foo
            - printenv
            - mkdir -p test && mount /dev/sdb test
