resources:
  - name: reportsFS_x8664_C7
    type: FileSpec
    configuration:
      sourceArtifactory: entArt
      pattern: "pipelines-artifacts/reports/reports-x86_64-CentOS_7-*.tar.gz"
      recursive: false
  - name: reportsFS_x8664_U18
    type: FileSpec
    configuration:
      sourceArtifactory: entArt
      pattern: "pipelines-artifacts/reports/reports-x86_64-Ubuntu_18.04-*.tar.gz"
pipelines:
  - name: basic_c7
    steps:
      - name: 1p1
        type: Bash
        configuration:
          inputResources:
            - name: reportsFS_x8664_U18
          runtime:
            type: image
            image:
              custom:
                name: pipelines-docker.jfrog.io/jfrog/pipelines-u18
                tag: base
        execution:
          onExecute:
            - echo 1
      - name: 1p2
        type: Bash
        configuration:
          inputResources:
            - name: reportsFS_x8664_U18
          runtime:
            type: image
            image:
              custom:
                name: pipelines-docker.jfrog.io/jfrog/pipelines-c7
                tag: base
        execution:
          onExecute:
            - echo 1
      - name: second
        type: Bash
        configuration:
          inputSteps:
            - 1p1
            - 1p2
          inputResources:
            - name: reportsFS_x8664_C7
          runtime:
            type: image
            image:
              custom:
                name: pipelines-docker.jfrog.io/jfrog/pipelines-c7
                tag: base
        execution:
          onExecute:
            - echo 1
          
