resources:
  - name: git
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master 

pipelines:
  - name: basic1
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
# #           inputResources:
# #            - name: git
#           environmentVariables:
#             foo: bar
#           runtime:
#             type: host
        execution:
          onExecute:
            - printenv
            - echo lol
            - add_pipeline_variables foo=bar
            - echo loool
      - name: second
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: foo
          dockerImageTag: foo
          inputResources:
            - name: git
#       - name: third
#         type: Bash
#         configuration:
#           #inputResources:
#           #  - name: git
#           inputSteps:
#             - name: basic
#             - name: second
#           environmentVariables:
#             foo: bar
#           runtime:
#             type: host
#         execution:
#           onExecute:
#             - echo $foo
          
