pipelines:
  - name: basic_podman
    steps:
      - name: basic_podman
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: localhost/podmaninsideimage
                tag: 1
        execution:
          onExecute:
            - echo hi
