resources:
  - name: git
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: bharath_github
      branches:
        include: master
  - name: buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: foo
      buildNumber: 1
  - name: buildInfoDup
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: foo
      buildNumber: 1

pipelines:
  - name: basic
    steps:
      - name: step1
        type: Bash
        configuration:
          runtime:
            type: host
          outputResources:
            - name: buildInfo
        execution:
          onExecute:
            - sleep 2m
      - name: step2
        type: Bash
        configuration:
          runtime:
            type: host
          inputSteps:
            - name: step1
          inputResources:
            - name: git
          outputResources:
            - name: buildInfoDup
        execution:
          onExecute:
            - sleep 2m
      - name: step3
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: git
            - name: buildInfoDup
        execution:
          onExecute:
            - sleep 2m
