resources:
  - name: github_1
    type: GitRepo
    configuration:
      path: bharath92/gitIssues
      gitProvider: bharath_github
      buildOn:  # optional
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: true
  - name: bitbucket_1
    type: GitRepo
    configuration:
      path: bharath92/sample-runsh
      gitProvider: bitbucket
      buildOn:  # optional
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: true
  - name: gitlab_1
    type: GitRepo
    configuration:
      path: Bharath92/samplePyt
      gitProvider: gitlab
      buildOn:  # optional
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: true
  - name: my_aql
    type: Aql
    configuration:
      sourceArtifactory: art
      query: "lol"
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
  - name: fileIntegrationResource
    type: FileSpec
    configuration:      
      sourceArtifactory: art
  - name: imageName
    type: Image
    configuration:
       registry: art
       sourceRepository: lol
       imageName: imageRepo/imageName
       imageTag: lol 
       autoPull: true   



pipelines:
  - name: basic3
    steps:
      - name: test
        type: Bash
        configuration:
          inputResources:
            - name: github
            - name: bitbucket
            - name: gitlab
        execution:
          onExecute:
            - printenv

