pipelines:
  - name: basic_again
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: 042add4d7132.ngrok.io/bharathdocker/bharath92/pipelines
                tag: master
                sourceRepository: bharathdocker
                registry: localart
        execution:
          onExecute:
            - echo 'Hello World!!!'
          
