resources:
  - name: git
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master 
  - name: cron
    type: CronTrigger
    configuration:
      interval: '*/2 * * *'

pipelines:
  - name: noagbasic1
    steps:
      - name: noagbasic
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - sleep 2m
      - name: noagbasicparallel
        type: Bash
        configuration:
          inputSteps:
            - name: noagbasic
          runtime:
            type: host
        execution:
          onExecute:
            - sleep 1m
      - name: noagbasic2
        type: Bash
        configuration:
          inputResources:
            - name: git
          inputSteps:
            - name: noagbasic
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - sleep 3m
      - name: noagbasic3
        type: Bash
        configuration:
          outputResources:
            - name: cron
          inputSteps:
            - name: noagbasic2
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - write_output cron "foo=$run_number"
            - sleep 1m
      - name: noagbasic4
        type: Bash
        configuration:
          inputSteps:
            - name: noagbasic3
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - sleep 1m
      - name: noagbasic5
        type: Bash
        configuration:
          inputSteps:
            - name: noagbasic4
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - sleep 1m
