pipelines:
  - name: basic_again
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: custom
            image:
              custom:
                name: test
                tag: test
                sourceRepository: test
                registry: art
        execution:
          onExecute:
            - echo 'Hello World!!!'
          
