resources:
  - name: git
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: bharath_github
      branches:
        include: test

pipelines:
  - name: basic
    steps:
      - name: basic
        type: Bash
        configuration:
          inputResources:
            - name: git
        execution:
          onExecute:
            - echo hi
