pipelines:
  - name: basic_again
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: jfrog/pipelines-u16node
                tag: base
                sourceRepository: pipelines-docker
                registry: art
        execution:
          onExecute:
            - echo 'Hello World!!!'
          
