resources:
  - name: git1
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: bharath_github
      branches:
        include: master
  - name: git2
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: bharath_github
      branches:
        include: master
      files:
        include: \btestdir\/file1\b
  - name: git3
    type: GitRepo
    configuration:
      path: ~bharathu/poc
      gitProvider: bharath_bbs
      branches:
        include: master
  - name: git4
    type: GitRepo
    configuration:
      path: bharath92/multibranch-pipelines
      gitProvider: bharath_github
      branches:
        include: \b.+\b
     
pipelines:
  - name: check1
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: git1
        execution:
          onExecute:
            - echo hi
  - name: check2
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: git2
        execution:
          onExecute:
            - echo hi
  - name: check3
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: git3
        execution:
          onExecute:
            - echo hi
