resources:
  - name: git_repro
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: bharath_github
      branches:
        include: master

pipelines:
  - name: repro
    steps:
      - name: basic
        type: Bash
        configuration:
          inputResources:
            - name: git_repro
          runtime:
            type: host
        execution:
          onExecute:
            - echo hi
