pipelines: 
  - name: test
    steps: 
      - name: Start
        type: Bash
        configuration: 
          runtime:
            type: host
        execution: 
          onExecute: 
            - echo "It's a start."
      - name: Step1
        type: Bash
        configuration: 
          chronological: true
          runtime:
            type: host
          inputSteps: 
            - name: Start
        execution: 
          onExecute: 
            - add_run_variables step1=foo
            - echo $step_id > foo
            - add_run_files foo foo
            - sleep 5
      - name: Step2
        type: Bash
        configuration:
          chronological: true
          runtime:
            type: host 
          inputSteps: 
            - name: Start
        execution: 
          onExecute: 
            - add_run_variables step2=bar
            - echo $step_id > bar
            - add_run_files bar bar
            - sleep 10
      - name: Step3
        type: Bash
        configuration: 
          runtime:
            type: host 
          inputSteps: 
            - name: Start
        execution: 
          onExecute: 
            - add_run_variables step3=baz
            - echo $step_id > baz
            - add_run_files baz baz
            - sleep 15
      - name: Finish
        type: Bash
        configuration: 
          nodePool: u16-aws
          runtime:
            type: image
            image:
              custom:
                registry: aws_creds
                name: 754160106182.dkr.ecr.us-east-1.amazonaws.com/jfbeta/ubuntu
                tag: latest
                region: us-east-1
          inputSteps: 
            - name: Step1
            - name: Step2
            - name: Step3
        execution: 
          onExecute:
            - echo hi
      - name: u18_aws
        type: Bash
        configuration: 
          nodePool: u18-aws
          runtime:
            type: image
            image:
              custom:
                registry: gcloud_creds
                name: shipbeta00/ubuntu
                tag: latest
          inputSteps: 
            - name: Finish
        execution: 
          onExecute:
            - echo hi
      - name: c7_aws
        type: Bash
        configuration: 
          nodePool: c7-aws
          runtime:
            type: image
            image:
              custom:
                registry: jfrog_creds
                name: jfrogpipelines.azurecr.io/alpine:latest
                tag: latest 
          inputSteps: 
            - name: Finish
        execution: 
          onExecute:
            - echo hi
      - name: u18_gcp
        type: Bash
        configuration: 
          nodePool: u18-gcp
          runtime:
            type: image
            image:
              custom:
                registry: aws_creds
                name: 754160106182.dkr.ecr.us-east-1.amazonaws.com/jfbeta/ubuntu
                tag: latest
                region: us-east-1
          inputSteps: 
            - name: Finish
        execution: 
          onExecute:
            - echo hi
      - name: u16_gcp
        type: Bash
        configuration: 
          nodePool: u16-gcp
          runtime:
            type: image
            image:
              custom:
                registry: jfrog_creds
                name: jfrogpipelines.azurecr.io/alpine:latest
                tag: latest
          inputSteps: 
            - name: Finish
        execution: 
          onExecute:
            - echo hi
      - name: c7_gcp
        type: Bash
        configuration: 
          nodePool: c7-gcp
          runtime:
            type: image
            image:
              custom:
                registry: gcloud_creds
                name: shipbeta00/ubuntu
                tag: latest
          inputSteps: 
            - name: Finish
        execution: 
          onExecute:
            - echo hi
      - name: u18_az
        type: Bash
        configuration: 
          nodePool: u18-az
          runtime:
            type: image
            image:
              custom:
                registry: jfrog_creds
                name: jfrogpipelines.azurecr.io/alpine:latest
                tag: latest 
          inputSteps: 
            - name: Finish
        execution: 
          onExecute:
            - echo hi
      - name: u16_az
        type: Bash
        configuration: 
          nodePool: u16-az
          runtime:
            type: image
            image:
              custom:
                registry: gcloud_creds
                name: shipbeta00/ubuntu
                tag: latest
          inputSteps: 
            - name: Finish
        execution: 
          onExecute:
            - echo hi
      - name: c7_az
        type: Bash
        configuration: 
          nodePool: c7-az
          runtime:
            type: image
            image:
              custom:
                registry: aws_creds
                name: 754160106182.dkr.ecr.us-east-1.amazonaws.com/jfbeta/ubuntu
                tag: latest
                region: us-east-1
          inputSteps: 
            - name: Finish
        execution: 
          onExecute:
            - echo hi
