resources:
  - name: test
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
#       branches:
#         include: master
#         exclude: foo
      tags:
        include: moo*
        exclude: boo
#       files:
#         include: foo.yml
#         exclude: boo.yml
      pullRequestSourceBranches:
        include: abc
        exclude: def
      pullRequestTargetBranches:
        include: qwerty
        exclude: poiuy
      buildOn:
        commit: true
        pullRequestCreate: true
        pullRequestClose: true
        releaseCreate: true
        tagCreate: true
pipelines:
  - name: basic
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: test
        execution:
          onExecute:
            - echo foo
