resources:
  - name: dockerbuild_gitRepo
    type: gitRepo
    repoPath: bharath92/gitIssues
    configuration:
      integrationName: bharath_github
    version:
      sha: master
  - name: buildInfo
    type: buildInfo
    version:
      buildName: app
      buildNumber: 1
    
pipelines:
  - name: app
    steps:
      - name: build_image
        type: build
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: mill.jfrog.info:12052/docker/bharath-gitissues
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        requires:
          integrations:
            - art
          resources:
            - dockerbuild_gitRepo
            
      - name: push_image
        type: push
        setup:
          push:
            targetRepo: docker
            scan: true
        requires:
          integrations:
            - art
        triggeredBy:
          steps:
            - build_image
            
#      - name: publish_build
#        type: publish
#        requires:
#          integrations:
#            - art
#        outputResources:
#          - buildInfo
  - name: scan_pipelinne
    steps:
      - name: scan_build
        type: scan
        setup:
          scan:
            buildName: $BUILD_NAME
            buildNumber: $BUILD_NUMBER
        requires:
          integrations:
            - art
        triggeredBy:
          resources:
            - buildInfo
