pipelines:
  - name: matrix
    steps:
      - name: matrix
        type: Matrix
        stepletMultipliers:
          fastFail: true
          environmentVariables:
            - foo: 4
              bar: echo
            - foo: 1
              bar: echo hi
            - foo: 8
              bar: abc
            - foo: 16
              bar: echo boo
        configuration:
#           multiNode: true
          runtime:
            type: host
        execution:
          onExecute:
            - echo $foo
            - for (( k = 0; k < 5; ++k )); do   echo $k; echo $foo; sleep $(( foo*k )); done
            - $bar
