pipelines:
  - name: basic
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - master
        execution:
          onExecute:
            - echo 1
          
