resources:
  - name: kermit_artifactory_go_example
    type: GitRepo
    configuration:
      path: bharath92/artifactory-go-example
      gitProvider: github
  - name: go_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: kermit_art
      buildName: go_example_build
      buildNumber: 1
  - name: unsigned_release_bundle
    type: ReleaseBundle
    configuration:
      sourceArtifactory: kermit_art
      name: go_test_bundle
      version: v1.0
  - name: signed_release_bundle
    type: ReleaseBundle
    configuration:
      sourceArtifactory: kermit_art
      name: go_test_bundle
      version: v1.0
  - name: promoted_go_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: kermit_art
      buildName: promote_go_build
      buildNumber: 1
  - name: distribution_rule
    type: DistributionRule
    configuration:
      sourceArtifactory: kermit_art
      cityName: "*"
      serviceName: "*"
      siteName: "*"
      countryCodes:
        - CN
  - name: distribution_rule2
    type: DistributionRule
    configuration:
      sourceArtifactory: kermit_art
      cityName: "*"
      serviceName: "*"
      siteName: "*"
      countryCodes:
        - EU
 
pipelines:
  - name: go_example_build
    steps:
      - name: build_go
        type: GoBuild
        configuration:
          sourceLocation: .
          repository: go
          outputLocation: /tmp/dist
          outputFile: hello
          inputResources:
            - name: kermit_artifactory_go_example
          integrations:
            - name: kermit_art
        execution:
          onStart:
            - wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
            - sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
            - export PATH=$PATH:/usr/local/go/bin
            - go version
      - name: push_go_binary
        type: PushArtifactoryPackage
        configuration:
          targetRepo: go_test
          integrations:
            - name: kermit_art
          inputSteps:
            - name: build_go
      - name: publish_go_build
        type: PublishBuildInfo
        configuration:
          integrations:
            - name: kermit_art
          inputSteps:
            - name: push_go_binary
          outputResources:
            - name: go_build_info
      - name: promote_go_build
        type: PromoteBuild
        configuration:
          targetRepo: promoted_go_test
          integrations:
            - name: kermit_art
          inputSteps:
            - name: publish_go_build
          outputResources:
            - name: promoted_go_build_info
      - name: create_release_bundle
        type: CreateReleaseBundle
        configuration:
          dryRun: false
          releaseBundleName: go_test_build
          releaseBundleVersion: v1.0
          sign: false
          inputResources:
            - name: promoted_go_build_info
          integrations:
            - name: kermit_art
          outputResources:
            - name: unsigned_release_bundle
      - name: sign_release_bundle
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: unsigned_release_bundle
          integrations:
            - name: kermit_art
          outputResources:
            - name: signed_release_bundle
      - name: distribute_signed_release_bundle
        type: DistributeReleaseBundle
        configuration:
          dryRun: true
          inputResources:
            - name: signed_release_bundle
            - name: distribution_rule
            - name: distribution_rule2
          integrations:
            - name: kermit_art
      
