pipelines: 
  - name: test
    steps: 
      - name: Start
        type: Bash
        configuration: 
          runtime:
            type: host
        execution: 
          onExecute: 
            - echo "It's a start."
      - name: Step1
        type: Bash
        configuration: 
          chronological: true
          runtime:
            type: host
          inputSteps: 
            - name: Start
        execution: 
          onExecute: 
            - add_run_variables step1=foo
            - echo $step_id > foo
            - add_run_files foo foo
            - sleep 5
      - name: Step2
        type: Bash
        configuration:
          chronological: true
          runtime:
            type: host 
          inputSteps: 
            - name: Start
        execution: 
          onExecute: 
            - add_run_variables step2=bar
            - echo $step_id > bar
            - add_run_files bar bar
            - sleep 10
      - name: Step3
        type: Bash
        configuration: 
          chronological: true
          runtime:
            type: host 
          inputSteps: 
            - name: Start
        execution: 
          onExecute: 
            - add_run_variables step3=baz
            - echo $step_id > baz
            - add_run_files baz baz
            - sleep 15
      - name: Finish
        type: Bash
        configuration: 
          runtime:
            type: host 
          inputSteps: 
            - name: Step1
            - name: Step2
            - name: Step3
        execution: 
          onExecute: 
            - echo "Step1 $step1"
            - echo "Step2 $step2"
            - echo "Step3 $step3"
            - echo "$builder_api_token"
