resources:
  - name: git
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master 
  - name: cron
    type: CronTrigger
    configuration:
      interval: '*/2 * * *'

pipelines:
  - name: basic1
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - echo lol
            - add_pipeline_variables foo=bar
            - echo loool
      - name: basic2
        type: Bash
        configuration:
          affinityGroup: foo
          inputResources:
            - name: git
          inputSteps:
            - name: basic
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - sleep 5m
      - name: basic3
        type: Bash
        configuration:
          affinityGroup: foo
          outputResources:
            - name: cron
          inputSteps:
            - name: basic2
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - write_output cron "foo=$run_number"
            - sleep 1m
