pipelines:
  - name: windows
    steps:
      - name: windows
        type: PowerShell
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - echo lol
