pipelines:
  - name: test
    steps:
      - name: test
        type: PowerShell
        runtime:
          type: host
        configuration:
          nodePool: win_2019
          integrations:
            - name: s_artifactory
        execution:
          onExecute:
            - docker ps
