resources:
  - name: basicgit
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master
pipelines:
  - name: basic_git
    steps:
      - name: basic_git
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: bharath92/pipelines
                tag: min
#           inputResources:
#             - name: basicgit
        execution:
          onExecute:
            - echo hiii
            - ls -al $run_dir
            - ls -al $pipeline_workspace_dir
            - chown -R root:root $pipeline_workspace_dir/
            - chmod -R 0777 $run_dir
            - touch /tmp/foo
            - touch $run_dir/foo
            - printenv
            - mkdir -p test && mount /dev/sdb test
