resources:
  - name: extensionres
    type: shippable/sampleResource
    configuration:
      resourceFoo: 1
pipelines:
  - name: extensiontest
    steps:
      - name: extensiontest
        type: shippable/sampleStep
        configuration:
          foo: abc
          integrations:
            - name: art
          inputResources:
            - name: extensionres
