pipelines:
  - name: basic_again
    steps:
      - name: test
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - printenv

