resources:
  - name: app12
    type: GitRepo
    configuration:
      path: bharath92/admiral
      gitProvider: bharath_github

pipelines:

  - name: test_pipeline2
    steps:
      - name: test_func2
        type: Bash
        configuration:
          inputResources:
            - name: app12
        execution:
          onExecute:
            - echo hi
            - write_output app12 imageTag=v1.0.0
            - echo bi
        
