resources:
  - name: app12
    type: GitRepo
    configuration:
      path: bharath92/admiral
      gitProvider: bharath_github
  - name: image
    type: Image
    configuration:
      registry: art
      sourceRepository: lol
      imageName: bharath92/gitissues
      imageTag: lol
pipelines:

  - name: test_pipeline2
    steps:
      - name: test_func1
        type: Bash
        configuration:
          affinityGroup: same
          inputResources:
            - name: app12
          outputResources:
            - name: image
        execution:
          onExecute:
            - echo hi
            - sleep 1
            - echo bi
        
     - name: test_func2
        type: Bash
        configuration:
          affinityGroup: same
          inputSteps:
            - name: test_func1
        execution:
          onExecute:
            - echo hi
            - sleep 1m
