resources:
  - name: app12
    type: GitRepo
    configuration:
      path: bharath92/admiral
      gitProvider: bharath_github
  - name: image
    type: Image
    configuration:
      registry: art
      sourceRepository: lol
      imageName: bharath92/gitissues
      imageTag: lol
pipelines:

  - name: test_pipeline1
    steps:
      - name: step1
        type: Bash
        configuration:
          affinityGroup: same
        execution:
          onExecute:
            - echo hi
            - sleep 1
            - echo bi
        
      - name: step2
        type: Bash
        configuration:
          affinityGroup: same
          inputSteps:
            - name: test1
        execution:
          onExecute:
            - echo hi
            - sleep 1m
