resources:
  - name: pvt_repo
    type: gitRepo
    repoPath: bharath92/api # private git repository
    configuration:
      integrationName: bharath_github
      branches:
        only: master
    initialVersion:
      sha: master
  - name: pub_repo
    type: gitRepo
    repoPath: bharath92/admiral # private git repository
    configuration:
      integrationName: bharath_github
      branches:
        only: master
    initialVersion:
      sha: master
  - name: buildInfo
    type: buildInfo
    initialVersion:
      buildName: test
      buildNumber: 1
  - name: buildInfo2
    type: buildInfo
    initialVersion:
      buildName: test
      buildNumber: 1
pipelines:
  - name: fan_out_in
    steps:
      - name: publish
        type: publish
        setup:
          environmentVariables:
            normal:
              buildName: boo
              buildNumber: 1
          #publish:
          #  envInclude: "test"
          #  envExclude: "boo"
        requires:
          resources:
            - pub_repo
          integrations:
          #  - bharath_github
            - art
#        outputResources:
#          - buildInfo
          #- buildInfo2
#      - name: sleep
#        type: bash
#        configuration:
#          affinityGroup: foo
#        #  timeoutSeconds: 10
#        requires:
#          resources:
#            - pub_repo
#        execution:
#          onExecute:
#            - echo 1
#            - cat $STEP_JSON_PATH
#            #- sleep 2m
#            - echo 2
#            - printenv
#            - sleep 5
#      - name: no_sleep
#        type: bash
#        configuration:
#          affinityGroup: foo
#        triggeredBy:
#          steps:
#            - sleep
#        execution:
#          onExecute:
#            - sleep 15
#      - name: test_pvt_git
#        type: bash
#        setup:
#          runtime:
#            type: host
#        requires:
#          resources:
#            - pub_repo
#            - pvt_repo
#        execution:
#          onExecute:
#            - printenv
#            - ls $res_pvt_repo_resourcePath
#            - sleep 3m
#      - name: start_foi
#        type: bash
#        configuration:
#          affinityGroup: test
#        execution:
#          onExecute:
#            - echo "start"
#      - name: top1_foi
#        type: bash
#        configuration:
#          priority: 1
#          affinityGroup: test
#        triggeredBy:
#          steps:
#            - start_foi
#        execution:
#          onExecute:
#            - echo "top1"
#      - name: bottom1_foi
#        type: bash
#        configuration:
#          priority: 5
#          affinityGroup: test
#        triggeredBy:
#          steps:
#            - start_foi
#        execution:
#          onExecute:
#            - echo "bottom1"
#            #- sleep 3m
#      - name: top2_foi
#        type: bash
#        configuration:
#          affinityGroup: test
#        triggeredBy:
#          steps:
#            - top1_foi
#        execution:
#          onExecute:
#            - echo "top2"
#            #- sleep 1h
#          onComplete:
#            - echo "hmmmm"
#          onFailure:
#            - echo "boo"
#      - name: top3_foi
#        type: bash
#        configuration:
#          affinityGroup: test
#        triggeredBy:
#          steps:
#            - top2_foi
#        execution:
#          onExecute:
#            - echo "start"
#      - name: final_foi
#        type: bash
#        configuration:
#          affinityGroup: test
#        triggeredBy:
#          steps:
#            - top3_foi
#            - bottom1_foi
#        execution:
#          onExecute:
#            - echo "start"
#      - name: outside_foi
#        type: bash
#        triggeredBy:
#          steps:
#            - top1_foi
#        execution:
#          onExecute:
#            - echo "no group"
