resources:
  - name: app1
    type: GitRepo
    repoPath: bharath92/admiral
    configuration:
      gitRepo: bharath_github

pipelines:

  - name: test_pipeline
    steps:
      - name: test_func
        type: Bash
        configuration:
          inputResources:
            - name: app1
        execution:
          onExecute:
            - echo hi
        
