jobs:
  - name: simple-runsh-u14
    type: runSh
    steps:
    - TASK:
        script: echo "Hello World!!!"
  - name: rsync-in-runsh
    type: runSh
    steps:
    - IN: pipelines_master
    - TASK:
        script: ls $PIPELINES_MASTER_PATH/syncRepo
