resources:
  - name: app1
    type: GitRepo
    configuration:
      path: bharath92/admiral
      gitProvider: bharath_github

pipelines:

  - name: test_pipeline
    steps:
      - name: test_func
        type: Bash
        configuration:
          inputResources:
            - name: app1
        execution:
          onExecute:
            - echo hi
        
