GitRepo:
  name: test_gitrepo
  gitProvider: bharath_github
  path: bharath92/sample-runsh
  branches:
    include: 'test_aws'

artifactoryIntegration: demoArt
  
Image:
  name: test
  sourceRepository: docker-local

DockerBuild:
  name: test_docker_build
  dockerImageName: test
  dockerFileName: Dockerfile
  dockerFileLocation: '.'
  dockerImageTag: ${run_number}

Pipeline:
  name: test_pipeline

DockerPush:
  name: foopush
  dockerImageName: test
  dockerFileName: Dockerfile
  targetRepository: docker-local
