# GitRepo:
#   name: fooGitRepo
#   gitProvider: github
#   path: bharath92/sample-runsh
#   branches:
#     include: 'master'

# artifactoryIntegration: art
  
# Image:
#   name: fooImage
#   sourceRepository: foo

# DockerBuild:
#   name: foobuild
#   dockerImageName: foo
#   dockerFileName: foo
#   dockerFileLocation: '.'
#   dockerImageTag: ${run_number}

# Pipeline:
#   name: foo

# DockerPush:
#   name: foopush
#   dockerImageName: foo
#   dockerFileName: foo
#   targetRepository: foo
start: &start
  - echo start
  - echo 11
  - echo 2a

resources:
  - name: basicgit
    type: GitRepo
    configuration:
      path: bharath92/sample-runSh
      gitProvider: github
      branches:
        include: master
#   - name: testaaaa
#     steps:
#       - name: testaaaa
#         type: Bash
#         execution:
#           onExecute:
#             - echo $UID
pipelines:
  - name: basic_git
    steps:
      - name: basic_git
        type: Bash
        configuration:
          runtime:
#             type: host
            type: image
#             image:
#               custom:
#                 name: bharath92/pipelines
#                 tag: min
#                 options: -e foo=bar
          inputResources:
            - name: basicgit
        execution:
          onStart: *start
          onExecute:
            - echo $UID
            - ls -la /var/opt/jfrog/pipelines
            - touch  /var/opt/jfrog/pipelines/boo
            - echo hiii
            - ls -al $run_dir
            - ls -al $pipeline_workspace_dir
            - lsblk
            - touch /tmp/foo
            - touch $run_dir/foo
            - printenv
            - mkdir -p test && mount /dev/sdb test
