GitRepo:
  name: fooGitRepo
  gitProvider: github
  path: bharath92/sample-runsh
#   branches:
#     include: 'master'

artifactoryIntegration: art
  
Image:
  name: fooImage
  sourceRepository: foo
  dockerImageName: foo
  autoPull: false

DockerBuild:
  name: fooDockerBuild
  dockerImageName: bharath92/alpine
  dockerFileName: Dockerfile
  dockerFileLocation: '.'
  dockerImageTag: ${run_number}

#Pipeline:
#  name: fooPipeline

DockerPush:
  name: fooDockerPush
  targetRepository: bharath92

# BuildInfo:
#   autoPublishBuildInfo: true
#   name: fooBuildInfo
