pipelines:
  - name: demo
    steps:
      - name: demo
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: docker.jfrog.io/jfrog/pipelines-u20node
                tag: 16.17.1-1196788
                sourceRepository: pipelines-docker
                registry: entplus
        execution:
          onExecute:
            - echo 'Hello World!!!'
          
